import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const policySchema = join(root, '..', 'dsh-agent-policy', 'policy-schema.mjs')

function stripModule(src) {
  return src
    .replace(/^import[\s\S]*?from '[^']+'\n+/gm, '')
    .replace(/^export \{[\s\S]*?\}\s*(from '[^']+')?\n+/gm, '')
    .replace(/^export /gm, '')
}

const parts = [
  stripModule(readFileSync(policySchema, 'utf8')),
  ...[
  'registry-i18n.mjs',
  'registry-marks.mjs',
  'registry-styles.mjs',
  'registry-presets.mjs',
  'registry-model.mjs',
  'registry-view.mjs',
  'registry-observe.mjs',
  'registry-settings.mjs',
  'registry-template.mjs',
  'registry-sidebar.mjs',
  'registry-preset-hide.mjs',
  'registry-isolate.mjs',
  'registry-runtime.mjs',
  ].map((file) => stripModule(readFileSync(join(root, file), 'utf8'))),
]

const banner = `// Generated by scripts/build-client.mjs. Do not edit by hand.

`
const body = `window.__ModuleLoader__.load({
  id: 'dsh-agent-registry',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports

    var name = 'dsh-agent-registry'
    var inject = ['slots', 'locale', 'sessions', 'workspaces', 'connection']

${parts.join('\n')}

    exports.name = name
    exports.inject = inject
    exports.apply = apply
    return module.exports
  },
})
`

const next = banner + body
const dest = join(root, 'client.js')
const check = process.argv.includes('--check')
if (check) {
  const current = readFileSync(dest, 'utf8')
  if (current !== next) {
    console.error('client.js is stale; run node scripts/build-client.mjs')
    process.exit(1)
  }
  process.exit(0)
}
writeFileSync(dest, next)
